import { Injectable } from '@angular/core';
import { Task } from '../models/task';

@Injectable({
  providedIn: 'root',
})
export class TaskService {
  taskList: Task[] = [
    // 🟨 Mis Tareas (0)
    {
      id: '1',
      icon: 'icon-add-to-list',
      text: 'Crear lista de tareas',
      completed: false,
      listId: '0',
    },
    {
      id: '2',
      icon: 'icon-chat',
      text: 'Responder mensajes',
      completed: false,
      listId: '0',
    },
    {
      id: '3',
      icon: 'icon-book',
      text: 'Leer un capítulo',
      completed: false,
      listId: '0',
    },
    {
      id: '4',
      icon: 'icon-clock',
      text: 'Programar alarma',
      completed: false,
      listId: '0',
    },
    {
      id: '5',
      icon: 'icon-inbox',
      text: 'Revisar correos',
      completed: true,
      listId: '0',
    },
    {
      id: '6',
      icon: 'icon-map',
      text: 'Revisar ruta',
      completed: true,
      listId: '0',
    },
    {
      id: '7',
      icon: 'icon-note',
      text: 'Tomar apuntes',
      completed: false,
      listId: '0',
    },
    {
      id: '8',
      icon: 'icon-thumbs-up',
      text: 'Dar feedback positivo',
      completed: true,
      listId: '0',
    },
    {
      id: '9',
      icon: 'icon-bookmarks',
      text: 'Marcar favoritos',
      completed: false,
      listId: '0',
    },

    // 🛒 Compra (1)
    {
      id: '10',
      icon: 'icon-bowl',
      text: 'Preparar desayuno',
      completed: false,
      listId: '1',
    },
    {
      id: '11',
      icon: 'icon-shopping-cart',
      text: 'Comprar leche',
      completed: false,
      listId: '1',
    },
    {
      id: '12',
      icon: 'icon-drink',
      text: 'Comprar refrescos',
      completed: false,
      listId: '1',
    },
    {
      id: '13',
      icon: 'icon-cake',
      text: 'Comprar pastel',
      completed: false,
      listId: '1',
    },
    {
      id: '14',
      icon: 'icon-shop',
      text: 'Ir al mercado',
      completed: false,
      listId: '1',
    },
    {
      id: '15',
      icon: 'icon-menu',
      text: 'Planificar menú semanal',
      completed: false,
      listId: '1',
    },
    {
      id: '16',
      icon: 'icon-shopping-basket',
      text: 'Comprar verduras',
      completed: false,
      listId: '1',
    },
    {
      id: '17',
      icon: 'icon-credit-card',
      text: 'Pagar la factura',
      completed: true,
      listId: '1',
    },

    // 🧼 Limpieza (2)
    {
      id: '18',
      icon: 'icon-trash',
      text: 'Sacar la basura',
      completed: false,
      listId: '2',
    },
    {
      id: '19',
      icon: 'icon-bucket',
      text: 'Lavar el baño',
      completed: false,
      listId: '2',
    },
    {
      id: '20',
      icon: 'icon-eraser',
      text: 'Limpiar pizarra',
      completed: false,
      listId: '2',
    },
    {
      id: '21',
      icon: 'icon-keyboard',
      text: 'Limpiar teclado',
      completed: false,
      listId: '2',
    },
    {
      id: '22',
      icon: 'icon-ruler',
      text: 'Medir estante',
      completed: false,
      listId: '2',
    },
    {
      id: '23',
      icon: 'icon-power-plug',
      text: 'Revisar conexiones',
      completed: false,
      listId: '2',
    },
    {
      id: '24',
      icon: 'icon-tools',
      text: 'Revisar herramientas',
      completed: false,
      listId: '2',
    },
    {
      id: '25',
      icon: 'icon-layers',
      text: 'Organizar carpetas',
      completed: false,
      listId: '2',
    },

    // 💼 Trabajo (3)
    {
      id: '26',
      icon: 'icon-calendar',
      text: 'Reunión con el equipo',
      completed: false,
      listId: '3',
    },
    {
      id: '27',
      icon: 'icon-classic-computer',
      text: 'Actualizar software',
      completed: true,
      listId: '3',
    },
    {
      id: '28',
      icon: 'icon-warning',
      text: 'Revisar alertas del sistema',
      completed: false,
      listId: '3',
    },
    {
      id: '29',
      icon: 'icon-remove-user',
      text: 'Eliminar usuarios inactivos',
      completed: false,
      listId: '3',
    },
    {
      id: '30',
      icon: 'icon-document-landscape',
      text: 'Formatear documento',
      completed: true,
      listId: '3',
    },
    {
      id: '31',
      icon: 'icon-cloud',
      text: 'Subir archivos a la nube',
      completed: false,
      listId: '3',
    },
    {
      id: '32',
      icon: 'icon-cog',
      text: 'Revisar configuración',
      completed: false,
      listId: '3',
    },
    {
      id: '33',
      icon: 'icon-camera',
      text: 'Tomar fotos del producto',
      completed: false,
      listId: '3',
    },
    {
      id: '34',
      icon: 'icon-mouse',
      text: 'Revisar periféricos',
      completed: false,
      listId: '3',
    },
    {
      id: '35',
      icon: 'icon-phone',
      text: 'Llamar a soporte',
      completed: false,
      listId: '3',
    },
    {
      id: '36',
      icon: 'icon-briefcase',
      text: 'Preparar maletín',
      completed: true,
      listId: '3',
    },
    {
      id: '37',
      icon: 'icon-video',
      text: 'Editar video',
      completed: false,
      listId: '3',
    },
    {
      id: '38',
      icon: 'icon-printer',
      text: 'Imprimir boletines',
      completed: false,
      listId: '3',
    },
    {
      id: '39',
      icon: 'icon-lab-flask',
      text: 'Hacer pruebas QA',
      completed: false,
      listId: '3',
    },
    {
      id: '40',
      icon: 'icon-pencil',
      text: 'Escribir reporte',
      completed: false,
      listId: '3',
    },

    // 💊 Salud (4)
    {
      id: '41',
      icon: 'icon-heart',
      text: 'Tomar presión',
      completed: false,
      listId: '4',
    },
    {
      id: '42',
      icon: 'icon-lifebuoy',
      text: 'Leer documentación',
      completed: true,
      listId: '4',
    },
    {
      id: '43',
      icon: 'icon-save',
      text: 'Guardar respaldo',
      completed: true,
      listId: '4',
    },

    // 🎮 Ocio (5)
    {
      id: '44',
      icon: 'icon-game-controller',
      text: 'Sesión de videojuegos',
      completed: true,
      listId: '5',
    },
    {
      id: '45',
      icon: 'icon-controller-fast-backward',
      text: 'Revisar grabación',
      completed: false,
      listId: '5',
    },
    {
      id: '46',
      icon: 'icon-controller-play',
      text: 'Reproducir presentación',
      completed: true,
      listId: '5',
    },
    {
      id: '47',
      icon: 'icon-music',
      text: 'Escuchar música',
      completed: false,
      listId: '5',
    },
    {
      id: '48',
      icon: 'icon-laptop',
      text: 'Revisar portátil',
      completed: false,
      listId: '5',
    },
    {
      id: '49',
      icon: 'icon-tv',
      text: 'Configurar Smart TV',
      completed: false,
      listId: '5',
    },
    {
      id: '50',
      icon: 'icon-upload',
      text: 'Subir informe',
      completed: true,
      listId: '5',
    },
  ];

  getTasks() {
    return this.taskList;
  }
}
